// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkqNDNdFrqWrjG4hVMVgEq0V4nJylccwE',
    appId: '1:656478835360:web:a4a9fd8c4a9ddc5c5bafc5',
    messagingSenderId: '656478835360',
    projectId: 'studyspotdiscover',
    authDomain: 'studyspotdiscover.firebaseapp.com',
    databaseURL: 'https://studyspotdiscover-default-rtdb.firebaseio.com',
    storageBucket: 'studyspotdiscover.appspot.com',
    measurementId: 'G-L1TVBQNZNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-lsZLyFZxWwzBHkUEGta1JUzUIMeLqS8',
    appId: '1:656478835360:android:834f56246254a7815bafc5',
    messagingSenderId: '656478835360',
    projectId: 'studyspotdiscover',
    databaseURL: 'https://studyspotdiscover-default-rtdb.firebaseio.com',
    storageBucket: 'studyspotdiscover.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnLx6B-06AXu_Kyis2KxqAd_sVa-xtC0o',
    appId: '1:656478835360:ios:f028819249ab0dfa5bafc5',
    messagingSenderId: '656478835360',
    projectId: 'studyspotdiscover',
    databaseURL: 'https://studyspotdiscover-default-rtdb.firebaseio.com',
    storageBucket: 'studyspotdiscover.appspot.com',
    iosBundleId: 'com.example.studyspotDiscover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnLx6B-06AXu_Kyis2KxqAd_sVa-xtC0o',
    appId: '1:656478835360:ios:58d21f2db08b48395bafc5',
    messagingSenderId: '656478835360',
    projectId: 'studyspotdiscover',
    databaseURL: 'https://studyspotdiscover-default-rtdb.firebaseio.com',
    storageBucket: 'studyspotdiscover.appspot.com',
    iosBundleId: 'com.example.studyspotDiscover.RunnerTests',
  );
}
